### ISSUE TITLE
Documentation to setup ONAP on Openshift

### ISSUE THREAD

**Issue by thefossgeek** [redhat-nfvpe/onap-on-openshift#1]
Hi,

Do you have documents to use this script to setup ONAP on openshift? I am looking for option to setup ONAP on Openshift. Any help will be really appreciated.

**Comment by fzdarsky** [comment]
@thefossgeek: Sorry that it took a while. Please find some basic documentation in the README.md now. Feel free to reopen the issue in case this documentation does not meet your needs.
